# A prefix used for every plugin
prefix = "<gray>[<yellow>KitPvP<gray>] <reset>"

[[languages]] # First: will be the default language
languageCode = "en"
displayName = "English (United States)"
headId = 44718

[[languages]]
languageCode = "de"
displayName = "Deutsch (Deutschland)"
headId = 43579

[[languages]]
languageCode = "es"
displayName = "Español (España)"
headId = 49449
